// Overview card showing AI executive summary paragraph and generation metadata
'use client';

import React from 'react';
import { Sparkles, Bot, Clock } from 'lucide-react';
import type { Summary } from '@/types';
import { formatDate } from '@/lib/utils';

interface OverviewCardProps {
	summary: Summary | null;
}

// Render AI executive summary card with badge indicating whether generated by LLM, seed, or fallback
export function OverviewCard({ summary }: OverviewCardProps) {
	if (!summary || !summary.overview) {
		return (
			<div className="rounded-2xl border border-dashed border-[var(--border-color)] bg-[var(--bg-secondary)]/50 p-6 text-center text-xs text-[var(--text-muted)]">
				No executive overview available for this meeting. Click 'Regenerate' to
				generate one.
			</div>
		);
	}

	const badgeConfig = {
		llm: {
			label: 'AI Generated',
			icon: Sparkles,
			className: 'bg-purple-500/10 text-purple-600 dark:text-purple-400',
		},
		seed: {
			label: 'Curated Summary',
			icon: Bot,
			className: 'bg-blue-500/10 text-blue-600 dark:text-blue-400',
		},
		fallback: {
			label: 'Automated Summary',
			icon: Clock,
			className: 'bg-amber-500/10 text-amber-600 dark:text-amber-400',
		},
	}[summary.generated_by as 'llm' | 'seed' | 'fallback'] || {
		label: 'AI Summary',
		icon: Sparkles,
		className: 'bg-[var(--brand-primary)]/10 text-[var(--brand-primary)]',
	};

	const BadgeIcon = badgeConfig.icon;

	return (
		<div className="rounded-2xl border border-[var(--border-color)] bg-[var(--bg-card)] p-5 shadow-xs">
			<div className="flex items-center justify-between">
				<h4 className="text-sm font-semibold text-[var(--text-primary)]">
					Executive Overview
				</h4>
				<span
					className={`inline-flex items-center gap-1 rounded-full px-2.5 py-0.5 text-[11px] font-medium ${badgeConfig.className}`}
				>
					<BadgeIcon className="h-3 w-3" />
					{badgeConfig.label}
				</span>
			</div>

			<p className="mt-3 text-sm text-[var(--text-secondary)] leading-relaxed">
				{summary.overview}
			</p>

			<div className="mt-4 flex items-center justify-between border-t border-[var(--border-color)]/60 pt-3 text-[11px] text-[var(--text-muted)]">
				<span>Summary created on {formatDate(summary.created_at)}</span>
				<span className="font-mono text-[10px]">
					Method: {summary.generated_by}
				</span>
			</div>
		</div>
	);
}
